### ISSUE TITLE
Reproduce DTU results

### ISSUE THREAD

**Issue by ChrisWu1997** [nianticlabs/diffusionerf#12]
Hi there,

Thanks for your excellent work. Do you mind sharing the DTU results somewhere or the shell script that can reproduce DTU results? I'm trying to reproduce the results on DTU but not sure if I have the correct setting.

**Comment by daniyar-niantic** [comment]
Hi. Yes, we can share the DTU results, could you tell us which images you want, i.e. 3-view, 6-view, 9-view, the scene and image name?

**Comment by ChrisWu1997** [comment]
Thanks for replying! 

Could you share all the results? That is, all the testing frames for 3/6/9 views on all the test scenes. Similar to what FreeNeRF shared [here](https://drive.google.com/drive/folders/1vUxq9mXeey1B1v2la8hNiNmZS0fwgKBo).

**Comment by jamiewynn** [comment]
Hi Chris,

Unfortunately we no longer have the original DTU few-view frames from the final run, but I did dig up some outputs from our parameter tuning that are almost the same as the final run. The only difference is that the patch regularisation weight in this run is very slightly lower. You can find it [here](https://storage.googleapis.com/niantic-lon-static/research/diffusionerf/dtu_param_tune_run.tar.gz). For each scene, the validation folder contains the images, as well as depth maps. I hope this will still be helpful to you.

Best,
Jamie
