### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by barbararoessle** [nianticlabs/diffusionerf#3]
Hi, 
This work is very interesting! 
Are you planning to release the code? If yes, what is the approximate timeline for that?
Thanks a lot!

**Comment by jamiewynn** [comment]
Hi Barbara,

Thanks for your interest - we are intending to release the code some time in the next few months.

**Comment by shivangi-aneja** [comment]
Hi,

Following up, when do you plan to release the source code?

**Comment by jamiewynn** [comment]
Hi Shivangi, we are hoping to release the code in the next couple of weeks (i.e. in time for CVPR).

**Comment by daniyar-niantic** [comment]
Thank you for the interest in the paper!

The code has been uploaded, please check the main repo.
