### ISSUE TITLE
LLFF_DEFAULT_PSEUDO_INTRINSICS

### ISSUE THREAD

**Issue by HkDzl** [nianticlabs/diffusionerf#6]
Hello! I'm a bit confused why LLFF_DEFAULT_PSEUDO_INTRINSICS is used instead of ground truth intrinsics.

**Comment by jamiewynn** [comment]
Hi there! These are the intrinsics that we use for rendering patches only. As such, there's no inherent reason why they need to precisely match the intrinsics of the training images. We could have used the ground truth intrinsics here, but the main reason we chose to fix them at this constant was for simplicity's sake - this saves us from worrying about how changing how we downsample the training images might also change the patches that we render, and there's something appealing about every rendered patch having the same FOV across all scenes even though the ground truth intrinsics vary throughout the dataset.

**Comment by HkDzl** [comment]
I understand. Thank you for your answer and your wonderful work.

**Comment by HkDzl** [comment]
> Hi there! These are the intrinsics that we use for rendering patches only. As such, there's no inherent reason why they need to precisely match the intrinsics of the training images. We could have used the ground truth intrinsics here, but the main reason we chose to fix them at this constant was for simplicity's sake - this saves us from worrying about how changing the resolution to which we downsample the training images might also change the patches that we render, and there's something appealing about every rendered patch having the same FOV across all scenes even though the ground truth intrinsics vary throughout the dataset.

I understand. Thank you for your answer and your wonderful work.

**Comment by Arcxml** [comment]
Hello, I want to know why using this will not have much impact on the result...
